apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-main

  template:
    metadata:
      labels:
        app: arcadia-main
    spec:
      containers:
        - name: arcadia-main
          image: sorinboia/arcadia-main:unit
          ports:
          - containerPort: 8080
        - image: sorinboia/app_protect:beta
          imagePullPolicy: Always
          name: nginx-ingress-protect
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          volumeMounts:
            - mountPath: /etc/nginx/7waf # mount nginx-conf volumn to /etc/nginx
              readOnly: true
              name: nginx-7waf
            - mountPath: /etc/nginx/conf.d # mount nginx-conf volumn to /etc/nginx
              readOnly: true
              name: nginxwaf-config
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              drop:
                - ALL
              add:
                - CAP_NET_BIND_SERVICE
            procMount: Default
            runAsUser: 0
            runAsGroup: 0
            privileged: true
      volumes:
        - name: nginxwaf-config
          configMap:
            name: nginxwaf-config
        - name: nginx-7waf
          configMap:
            name: nginx-7waf
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: arcadia-main
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: arcadia-main